-- ==========================================
-- OPENCLAW CONTENT AGENTS: SUPABASE SCHEMA
-- ==========================================

-- 1. Table: content_briefs (Generated by Agent 01 - Content Strategist)
CREATE TABLE IF NOT EXISTS public.content_briefs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT NOT NULL,
    target_keyword TEXT,
    secondary_keywords JSONB, -- Stored as a JSON array of strings
    outline TEXT,
    angle TEXT,
    status TEXT DEFAULT 'PENDING', -- PENDING, IN_PROGRESS, PUBLISHED
    word_count_target INTEGER,
    trend_score INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Table: content (Generated by Agent 02 - Blog Writer)
CREATE TABLE IF NOT EXISTS public.content (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    brief_id UUID REFERENCES public.content_briefs(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    category TEXT,
    html_content TEXT,
    seo_score INTEGER,
    live_url TEXT,
    featured_image_url TEXT,
    status TEXT DEFAULT 'PUBLISHED',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Table: post_performance (Generated by Agent 03 - Content Auditor)
CREATE TABLE IF NOT EXISTS public.post_performance (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    post_id UUID REFERENCES public.content(id) ON DELETE CASCADE,
    avg_position NUMERIC(5,2),
    clicks INTEGER,
    ctr NUMERIC(5,2),
    impressions INTEGER,
    score INTEGER,
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- DISABLE ROW LEVEL SECURITY (RLS) FOR AGENT ACCESS
-- By default, Supabase blocks unauthorized inserts. 
-- We disable this so the local backend Node.js scripts can insert rows seamlessly.
-- ==========================================

ALTER TABLE public.content_briefs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.content DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_performance DISABLE ROW LEVEL SECURITY;
